const datos = [
  {
    codigo: "1",
    nombre: "Francisco Narciso de Laprida",
    nacimiento: "28 de octubre de 1786, San Juan, Argentina.",
    fallecimiento: "22 de septiembre de 1829, Mendoza, Argentina (42 años).",
    nacionalidad: "Argentina",
    profesion: "Abogado y político argentino.",
    distrito: "San Juan",
    resumen:
      " Abogado y político argentino. Diputado por San Juan al Congreso de Tucumán. Presidió el mismo cuando se declaró la independencia del país el 9 de julio de 1816.",
    habilidades: [
      "★★★★☆ Derecho",
      "★★★★☆ Política",
      "★★☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1824 - Representó a San Juan en el Congreso Nacional, presidiendo el mismo durante unos meses.",
      "1820 - Asumió como ministro general de gobierno durante la gobernación de José Antonio Sánchez en la Provincia de San Juan.",
      "1816 - Diputado para el Congreso de Tucumán.",
      "1812 - electo síndico del Cabildo.",
    ],
    educacion: [
      "Colegio Nacional de Buenos Aires.",
      "Real Universidad de San Felipe.",
    ],
    aficiones:
      "Política, militancia en el Partido Unitario y estudio del derecho.",
    imagen: "../img/LapridaNarciso.jpg",
    youtube: "https://www.youtube.com/watch?v=9An9Ez-FpfM",
    wikipedia: "https://es.wikipedia.org/wiki/Francisco_Narciso_de_Laprida",
  },
  {
    codigo: "2",
    nombre: "Mariano Boedo",
    nacimiento: "25 de julio 1782, Salta, Argentina.",
    fallecimiento: "9 de abril de 1819, Buenos Aires, Argentina (36 años).",
    nacionalidad: "Argentina",
    profesion: "Abogado y político argentino.",
    distrito: "Salta",
    resumen:
      "Abogado y político argentino, diputado por Salta en el Congreso de Tucumán de 1816.",
    habilidades: [
      "★★★☆☆ Derecho",
      "★★★★☆ Política",
      "★☆☆☆☆ Militar",
      "★★★☆☆ Teología",
    ],
    experiencia: [
      "1816 - Diputado por Salta al mencionado Congreso de Tucumán.",
      "Secretario de la Real Audiencia de Buenos Aires.",
      "Asesor letrado y responsable de la intendencia.",
      " 1812 sería electo síndico del Cabildo.",
    ],
    educacion: [
      "	1805 - Abogado recibido en Universidad Mayor, Real y Pontificia San Francisco Xavier de Chuquisaca.",
      " Estudió en el Seminario de Loreto.",
    ],
    aficiones:
      "Gran debatiente, honesto y defensor de los derechos de los más necesitados.",
    imagen: "../img/BoedoMariano.jpg",
    youtube: "https://www.youtube.com/watch?v=8qqCBYKqb04",
    wikipedia: "https://es.wikipedia.org/wiki/Mariano_Boedo",
  },
  {
    codigo: "3",
    nombre: "José Mariano Serrano",
    nacimiento: "8 de septiembre, Villa Imperial de Potosí, Bolivia.",
    fallecimiento: "1851, Sucre, Bolivia (63 años).",
    nacionalidad: "Argentina y Boliviana.",
    profesion: "Jurista y político boliviano.",
    distrito: "Charcas",
    resumen:
      "Hombre de estado y jurista boliviano. Fue secretario y diputado en el Congreso de Tucumán del 9 de julio de 1816.",
    habilidades: [
      "★★★★☆ Derecho",
      "★★★★★ Política",
      "★☆☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1839 - Fue presidente interino de Bolivia.",
      "1830 - Presidió la Corte Suprema de Justicia de Bolivia.",
      "1825 - Representó a Chuquisaca en la asamblea que declaró la Independencia Boliviana.",
      "1824 - Fue secretario del gobierno de Salta.",
      "1816 - Fue elegido diputado por Charcas para el Congreso.",
    ],
    educacion: [
      "	1811 - Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca.",
    ],
    aficiones:
      "Revolucionario, conocimientos de la lengua quechua, afinidad a los dogmas de una monarquía constitucional.",
    imagen: "../img/SerranoJoseMariano.jpg",
    wikipedia:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Jos%C3%A9_Mariano_Serrano.jpg/220px-Jos%C3%A9_Mariano_Serrano.jpg",
  },
  {
    codigo: "4",
    nombre: "Juan José Paso",
    nacimiento: "2 de junio de 1758, Buenos Aires, Argentina.",
    fallecimiento:
      "10 de septiembre de 1833, Buenos Aires, Argentina (75 años).",
    nacionalidad: "Argentina",
    profesion: "Doctor en Leyes y político.",
    distrito: "Buenos Aires",
    resumen:
      "Nacido como Juan José Esteban del Passo, fue un doctor en leyes y político de las Provincias Unidas del Río de la Plata, que promovió la Revolución de Mayo.  Tuvo el honor de leer el  acta de la independencia.",
    habilidades: [
      "★★★★★ Derecho",
      "★★★★☆ Política",
      "★☆☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1822 - Diputado provincial en Buenos Aires.",
      "1816 - Diputado en el Congreso de Tucumán por Buenos Aires.",
      "1814 - Enviado en misión diplomática a Chile.",
      "1812 - Miembro del segundo Triunvirato.",
      "1811 - Miembro del primer Triunvirato.",
      "1811 - Integró la diputación que firmó en Montevideo el armisticio con el virrey Francisco Javier de Elío.",
      "1810 - Miembro de la Junta Grande.",
      "1810 - Secretario de hacienda de la Primera Junta.",
    ],
    educacion: [
      "1779 - Doctor en Leyes, Universidad Nacional de Córdoba.",
      "Colegio Monserrat, Córdoba.",
    ],
    aficiones:
      "Fundador de San José de Flores; partidario del Carlotismo y la monarquía Constitucional; afín a la Filosofía.",
    imagen: "../img/PasoJuanJose.jpg",
    youtube: "https://www.youtube.com/watch?v=GUhMm-Io6cw",
    wikipedia: "https://es.wikipedia.org/wiki/Juan_Jos%C3%A9_Paso",
  },
  {
    codigo: "5",
    nombre: "Antonio Sáenz.",
    nacimiento: "6 de junio de 1780, Buenos Aires, Argentina.",
    fallecimiento: "22 de julio de 1825, Buenos Aires, Argentina (45 años).",
    nacionalidad: "Argentina.",
    profesion: "Sacerdote, jurisconsulto y político.",
    distrito: "Buenos Aires",
    resumen:
      "Sacerdote, jurisconsulto y político argentino. Como diputado en el Congreso de Tucumán del 9 de julio de 1816 firmó la Declaración de la Independencia de Argentina. Principal promotor para la organización de la que sería la Universidad de Buenos Aires.",
    habilidades: [
      "★★★★☆ Derecho",
      "★★★☆☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★☆ Teología",
    ],
    experiencia: [
      "1822 y 1823 - Docente de las cátedras Derecho Natural y Gentes.",
      "1821 - Primer rector de la Universidad de Buenos Aires.",
      "1817 - Diputado por Buenos Aires.",
      "1816 - Capellán castrense y diputado por Buenos Aires al Congreso de Tucumán.",
      "1815 - fue designado miembro de la Junta de Observación que promulgó el Estatuto Provisional de 1815.",
      "1813 - Representante por la provincia de San Luis ante la Asamblea del año XIII.",
      "1812 - Formó parte de la Asamblea General.",
      "1811 - Integró la Junta Protectora de la libertad de la Imprenta.",
    ],
    educacion: [
      "1806 - Fue ordenado sacerdote en Buenos Aires.",
      "1804 - Bachiller en leyes en la Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca.",
    ],
    aficiones:
      "Promotor de la educación universitaria, activo miembro de la Logia Lautaro.",
    imagen: "../img/SaenzAntonio.jpg",
    youtube: "https://www.youtube.com/watch?v=yUCULiVbBqs",
    wikipedia: "https://es.wikipedia.org/wiki/Antonio_S%C3%A1enz",
  },
  {
    codigo: "6",
    nombre: "José Darregueira",
    nacimiento: "27 de enero de 1771, Monquegua, Perú.",
    fallecimiento: "1 de mayo de 1817, Buenos Aires, Argentina. (46 años)",
    nacionalidad: "Peruana",
    profesion: "Abogado y político.",
    distrito: "Buenos Aires",
    resumen:
      "Fue un hombre de estado y abogado de origen peruano que desempeñó sus funciones en Argentina. Fue diputado en el Congreso de Tucumán del 9 de julio de 1816, el cual declaró la Independencia Argentina.",
    habilidades: [
      "★★★★★ Derecho",
      "★★★★☆ Política",
      "★☆☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1817 - Diputado por Buenos Aires y asesor legal del Director Supremo Pueyrredón.",
      "1816 - Integrante del Congreso de Tucumán.",
      "1815 - Integrante de la cámara de apelaciones.",
      "1810 - Partícipe de la revolución de mayo.",
      "1795 -  Socio en el estudio de abogado de Vicente Anastasio Echevarría.",
    ],
    educacion: [
      "1794 - Doctor en leyes Universidad de Chuquisaca.",
      "Real Colegio de San Carlos.",
    ],
    aficiones:
      "Perteneciente a la Logia Lautaro, escritor de artículos periodísticos. Fiel defensor del unitarismo.",
    imagen: "../img/DarregueiraJose.jpg",
    youtube: "https://www.youtube.com/watch?v=i6nxZTXt1Dc",
    wikipedia: "https://es.wikipedia.org/wiki/Jos%C3%A9_Darregueira",
  },
  {
    codigo: "7",
    nombre: "Cayetano José Rodríguez",
    nacimiento: "1761, San Pedro, Argentina.",
    fallecimiento: "21 de enero de 1823, Buenos Aires, Argentina (62 años).",
    nacionalidad: "Argentina",
    profesion: "Fraile y sacerdote franciscano.",
    distrito: "Buenos Aires",
    resumen:
      "Fraile y sacerdote franciscano y poeta argentino. Fue diputado en el Congreso de Tucumán que declaró la Independencia Argentina el 9 de julio de 1816.",
    habilidades: [
      "★★☆☆☆ Derecho",
      "★★★☆☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★★Teología",
    ],
    experiencia: [
      "1822 - Fundó el periódico El Oficial del Día.",
      "1816 - Diputado del Congreso de Tucumán.",
      "1811 - Ministro Provincia de Buenos Aires.",
      "1810 a 1814 - Director de la Biblioteca Pública de Buenos Aires.",
      "1790 - Docente de teología, filosofía, hermenéutica y física en Conveno Franciscano.",
      "1783 - 1790 - Docente cátedras teología y filosofía en Universidad de Córdoba.",
    ],
    educacion: [
      "1783 - Sacerdote.",
      "Colegio del Convento de los Padres Franciscanos.",
    ],
    aficiones:
      "Poeta y escritor de Odas, autor del primer Himno Nacional, defensor de la iglesia católica contra el regalismo.",
    imagen: "../img/RodriguezCayetano.jpg",
    youtube: "https://www.youtube.com/watch?v=aPqjv9Ou-Bs&t=26s",
    wikipedia:
      "https://es.wikipedia.org/wiki/Cayetano_Jos%C3%A9_Rodr%C3%ADguez",
  },
  {
    codigo: "8",
    nombre: "Pedro Medrano",
    nacimiento: "26 de abril de 1769, Isla Gorriti, Uruguay.",
    fallecimiento: "3 de noviembre de 1840, Buenos Aires, Argentina (71 años)",
    nacionalidad: "Argentina y Uruguaya.",
    profesion: "Abogado, político y poeta.",
    distrito: "Buenos Aires",
    resumen:
      "Participó en el Cabildo abierto de 1810, donde se pronunció a favor de la causa criolla, y fue diputado en el Congreso de Tucumán, que declaró la Independencia Argentina el 9 de julio de 1816.",
    habilidades: [
      "★★★★★ Derecho",
      "★★★☆☆ Política",
      "★☆☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1821 - Secretario de la Junta de Representantes  y durante el gobierno de Rosas.",
      "1816 - Diputado en el Congreso de Tucumán, ejerciendo como primer presidente y dando el discurso inaugural.",
      "1815 - Fue uno de los autores del Estatuto provisional de 1815.",
      "1812 - Elegido como diputado para la que sería la Asamblea del Año XIII.",
      "ejerció como abogado en Buenos Aires, participando del Cabildo abierto del día 22 de mayo de 1810.",
    ],
    educacion: [
      "Doctor en leyes en la Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca.",
      "Realizó sus estudios superiores en el Colegio Monserrat de Córdoba.",
    ],
    aficiones:
      " Se destacó como orador y poeta. Escribió un largo romance titulado Carta de Celio a Armesto, de clara intención política; La Martiniana y la traducción al Poema de la Expedición al Desierto, de 1833-34.",
    imagen: "../img/MedranoPedro.jpg",
    youtube: "https://www.youtube.com/watch?v=6CB92kKNxuk",
    wikipedia: "https://es.wikipedia.org/wiki/Pedro_Medrano",
  },
  {
    codigo: "9",
    nombre: "Esteban Agustín Gascón",
    nacimiento: "9 de julio de 1764, Oruro, Bolivia.",
    fallecimiento: "25 de junio de 1824, Buenos Aires, Argentina (59 años).",
    nacionalidad: "Argentina y Boliviana.",
    profesion: "Abogado y político.",
    distrito: "Buenos Aires",
    resumen:
      "Esteban Agustín Gascón, también citado como Juan Agustín Gazcón  fue un político argentino de origen altoperuano participante del Congreso de Tucumán de 1816.",
    habilidades: [
      "★★★★★ Derecho",
      "★★★★☆ Política",
      "★★★★☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1822 - Camarista del Tribunal de Justicia de la provincia de Buenos Aires.",
      "1820 - Juez, diputado provincial y secretario de la Junta de representantes de Buenos Aires.",
      "1819 - Senador por Tucumán.",
      "1817 - Ministro de hacienda del Director Juan Martín de Pueyrredón.",
      "1816 - Diputado para el Congreso de Tucumán.",
      "1815 - Presidió la Junta de Observación.",
      "1813 a 1814 - Alcalde del Cabildo.",
      "1813 - Auditor general de guerra y asesor legal de sus jefes, el general José Rondeau primero, y luego Carlos María de Alvear.",
      "1813 - Soldado del ejército oriental.",
      "1813 - Soldado del ejército del norte, bajo las órdenes de Manuel Belgrano.",
      "1809 - Partició en la revolución de Chuquisaca.",
    ],
    educacion: [
      "Se doctoró en Derecho en la Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca.",
      "Real Colegio San Carlos de Buenos Aires.",
    ],
    aficiones: "Oposición total a la reformas religiosas.",
    imagen: "../img/GasconEstebanA.jpg",
    youtube: "https://www.youtube.com/watch?v=4W_z6zziTYg&t=7s",
    wikipedia: "https://es.wikipedia.org/wiki/Esteban_Agust%C3%ADn_Gasc%C3%B3n",
  },
  {
    codigo: "10",
    nombre: "Tomás de Anchorena",
    nacimiento: "29 de noviembre de 1783, Buenos Aires, Argentina.",
    fallecimiento: "29 de abril de 1847, Buenos Aires, Argentina (63 años).",
    nacionalidad: "Argentina y Boliviana.",
    profesion: "Político y abogado.",
    distrito: "Buenos Aires",
    resumen:
      "Político y abogado argentino, conocido por haber firmado, junto a otros 32 diputados, el acta de la Declaración de la independencia argentina.",
    habilidades: [
      "★★★★☆ Derecho",
      "★★★☆☆ Política",
      "★★☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1829 a 1832 - Ministro de Relaciones Exteriores bonaerense durante el primer gobierno de Juan Manuel de Rosas.",
      "1820 - Trabajó para el gobierno de Buenos Aires.",
      "1816 - Diputado por Buenos Aires en el Congreso de Tucumán.",
      "1811 a 1815 - Secretario del general Manuel Belgrano, en el ejército del Norte.",
      "1809 a 1810 - Participó activamente de la Revolución de Mayo.",
    ],
    educacion: [
      "Doctor en Leyes con título de la Universidad Mayor Real y Pontificia San Francisco Xavier de Chuquisaca.",
      "Estudió en el Real Colegio de San Carlos.",
    ],
    aficiones: "Padre devoto de 15 hijos. De fuertes ideas federales.",
    imagen: "../img/AnchorenaTomasDe.jpg",
    youtube: "https://www.youtube.com/watch?v=JdOyGuUJFYk&t=12s",
    wikipedia: "https://es.wikipedia.org/wiki/Tom%C3%A1s_de_Anchorena",
  },
  {
    codigo: "11",
    nombre: "Manuel Antonio Acevedo",
    nacimiento: "25 de mayo, Salta, Argentina",
    fallecimiento: "1 de octubre, Argentina (55 años)",
    nacionalidad: "Argentina",
    profesion: "Presbítero y abogado de Argentina.",
    distrito: "Catamarca",
    resumen:
      "Diputado del Congreso de Tucumán y uno de los primeros legisladores de Catamarca al ser nombrado vocal de la primera constituyente catamarqueña.",
    habilidades: [
      "★★★☆☆ Derecho",
      "★★★★☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★★ Teología",
    ],
    experiencia: [
      "1824 - Diputado por Catamarca en el Congreso General de 1824.",
      "1822 - Redactó el Proyecto de Constitución para la Provincia de Catamarca.",
      "1821 - Secretario de la Sala de Representantes de Buenos Aires.",
      "1816 - Diputado por la jurisdicción de la ciudad de Catamarca al Congreso de Tucumán.",
      "1807 - Parroco de Belén, Catamarca.",
      "1804 a 1806 - Cura párrico de Molinos, Valles Calchaquíes.",
      "1801 a 1804 - Cura párroco de Cachi, Valles Calchaquíes.",
      " 1799 - participó de la fundación de la Escuela de Filosofía en Salta.",
    ],
    educacion: ["Ordenado Presbítero", "Colegio Montserrat, Córdoba."],
    aficiones:
      "A favor de la institución de la monarquía incaica. Propuso que el monarca de la incipiente Argentina fuese un descendiente de los incas, en la sesión del 12 de julio de 1816.",
    imagen: "../img/AcevedoManuelAntonio.jpg",
    youtube: "https://www.youtube.com/watch?v=6CB92kKNxuk&t=3s",
    wikipedia: "https://es.wikipedia.org/wiki/Manuel_Antonio_Acevedo  ",
  },
  {
    codigo: "12",
    nombre: "José Eusebio Colombres",
    nacimiento: "6 de diciembre de 1778, San Miguel de Tucumán, Argentina.",
    fallecimiento: "11 de febrero de 1859, Salta, Argentina (80 años).",
    nacionalidad: "Argentina",
    profesion: "Político y Obispo Argentino.",
    distrito: "Catamarca",
    resumen:
      "Político y obispo argentino. Fue diputado por Catamarca durante el Congreso de Tucumán en 1816. ",
    habilidades: [
      "★★★☆☆ Derecho",
      "★★☆☆☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★★ Teología",
    ],
    experiencia: [
      "1858 - obispo de la Diócesis de Salta.",
      "1816 - Diputado en el congreso de Tucumán.",
    ],
    educacion: [
      "Doctor en Ley con título de la Universidad de San Carlos en Córdoba.",
      "1803 - Ordenado clérigo.",
    ],
    aficiones:
      " Participante de la Liga del Norte; impulsó la creación de una nueva Catedral de Salta y el desarrollo de la industria azucarera en Tucumán.",
    imagen: "../img/ColombresJoseEusebio.jpg",
    youtube: "https://www.youtube.com/watch?v=3iwOUiajlpc",
    wikipedia: "https://es.wikipedia.org/wiki/Jos%C3%A9_Eusebio_Colombres",
  },
  {
    codigo: "13",
    nombre: "Eduardo Pérez Bulnes",
    nacimiento: "12 de octubre de 1785, Córdoba, Argentina.",
    fallecimiento: "3 de marzo de 1851, Argentina (65 años).",
    nacionalidad: "Argentina",
    profesion: "Político",
    distrito: "Córdoba",
    resumen:
      "político argentino, líder federal Córdoba y miembro del Congreso de Tucumán; firmó el acta de la Independencia Argentina.",
    habilidades: [
      "★★☆☆☆ Derecho",
      "★★★★☆ Política",
      "★★★☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1824 - Diputado al Congreso General de 1824 en Buenos Aires.",
      "1820 - Diputado provincial.",
      "1816 - Diputado del Congreso de Tucumán.",
      "1811 - Regidor del Cabildo de Córdoba.",
      "1810 - Durante la Revolución de Mayo se enroló como oficial de las milicias urbanas de Córdoba.",
    ],
    educacion: [
      "Estudió derecho en la Universidad Nacional de Córdoba.",
      "Educado en Real Colegio Convictorio de Nuestra Señora de Monserrat.",
    ],
    aficiones:
      "Defensor del federalismo, opuesto a los Triunviratos y del Directorio. Posteriormente afín al unitarismo.",
    imagen: "../img/PerezBulnesEduardo.jpg",
    youtube: "https://www.youtube.com/watch?v=aPqjv9Ou-Bs&t=38s",
    wikipedia: "https://es.wikipedia.org/wiki/Eduardo_P%C3%A9rez_Bulnes",
  },
  {
    codigo: "14",
    nombre: "José Antonio Cabrera.",
    nacimiento: "28 de noviembre de 1768, Córdoba, Argentina.",
    fallecimiento: "15 de abril de 1820, Córdoba, Argentina (51 años).",
    nacionalidad: "Argentina",
    profesion: "Abogado y político.",
    distrito: "Córdoba",
    resumen:
      " Abogado y político argentino, miembro del Congreso de Tucumán, que declaró la independencia argentina.",
    habilidades: [
      "★★★★☆ Derecho",
      "★★★☆☆ Política",
      "★☆☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1816 - Diputado del Congreso de Tucumán.",
      "1815 - Dirigente en el partido federal y miembro de la primera legislatura provincial.",
      "1814 - Participó de una misión de paz con Artigas.",
      "1811 - Alcalde de primer voto del Cabildo de la ciudad de Córdoba.",
    ],
    educacion: [
      "licenciado en jurisprudencia en la Universidad Nacional de Córdoba.",
      "",
    ],
    aficiones:
      "De fuertes raíces federales, fue asesor letrado de los gobernadores del último período virreinal.",
    imagen: "../img/CabreraJoseAntonio.jpg",
    youtube: "https://www.youtube.com/watch?v=aPqjv9Ou-Bs&t=38s",
    wikipedia:
      "https://es.wikipedia.org/wiki/Jos%C3%A9_Antonio_Cabrera_(pol%C3%ADtico)",
  },
  {
    codigo: "15",
    nombre: "Jerónimo Salguero de Cabrera y Cabrera",
    nacimiento: "1774, Córdoba, Argentina.",
    fallecimiento: "mayo de 1840, Sucre, Bolivia (66 años).",
    nacionalidad: "Argentina",
    profesion: "Abogado y político",
    distrito: "Córdoba",
    resumen:
      "Abogado y político argentino, miembro del Congreso de Tucumán, que declaró la independencia argentina.",
    habilidades: [
      "★★★★★ Derecho",
      "★★★☆☆ Política",
      "★☆☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1831 a 1833 - Juez.",
      "1826 - Diputado del Congreso de Buenos Aires.",
      "1819 - Tesorero de la Casa de la Moneda.",
      "1816 - Diputado por Córdoba para el Congreso de Tucumán.",
      "1812 - Procurador general de Córdoba.",
    ],
    educacion: [
      "1796 - Recibido de doctor en Jurisprudencia.",
      "Educado en el Colegio Montserrat, Córdoba.",
    ],
    aficiones: "Defensor de las autonomías provinciales.",
    imagen: "../img/SalguerodeCabreraJeronimo.jpg",
    youtube: "https://www.youtube.com/watch?v=yUCULiVbBqs",
    wikipedia: "https://es.wikipedia.org/wiki/Jer%C3%B3nimo_Salguero",
  },
  {
    codigo: "16",
    nombre: "Teodoro Sánchez de Bustamante",
    nacimiento: "9 de noviembre de 1778, San Salvador de Jujuy, Argentina.",
    fallecimiento: "11 de mayo de 1851, Santa Cruz de la Sierra, Bolivia.",
    nacionalidad: "Argentina y Boliviana.",
    profesion: "Abogado y político.",
    distrito: "Jujuy",
    resumen:
      "Abogado y político argentino, que participó en el Congreso de Tucumán, y estuvo entre quienes declararon la Independencia Argentina.",
    habilidades: [
      "★★★★★ Derecho",
      "★★★★★ Política",
      "★★★☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1829 - Presidente de la legislatura.",
      "1826 - Teniente de Gobernación de Jujuy.",
      "1825 - Gobernador Interino de Salta.",
      "1820 a 1824 - Asesor del Gobernador de Córdoba Bustos.",
      "1819 - Redactor en la Constitución de 1819.",
      "1816 - Diputado para el Congreso de Tucumán.",
      "1812 - Auditor y secretario de guerra del Ejercito del Norte, participante de la Segunda Expedición auxiliadora y tercera campaña al Alto Perú.",
      "1812 - Fiscal de la cámara de apelaciones de Buenos Aires.",
      "1810 - Asesor letrado del Gobernador de Salta y fiscal de los fueros civil y criminal de la Audiencia de Buenos Aires.",
      "1810 - Alcalde de primer voto del Cabildo de Jujuy.",
      "1801 a 1809 - Fiscal de la Real Audiencia de Charcas y presidente de la Academia Carolina de Derecho.",
    ],
    educacion: [
      "1801 - Doctor en leyes - Universidad Mayor Real y Pontificia San Francisco Xavier de Chuquisaca.",
      "Estudios secundarios cursados en Buenos Aires.",
    ],
    aficiones:
      "Apoyó las ideas unitarias; fundó una escuela lancasteriana, brego por el desarrollo de las comunicaciones y las carreteras.",
    imagen: "../img/SanchesdeBustamanteTeodoro.jpg",
    youtube: "https://www.youtube.com/watch?v=iILAui9zTls",
    wikipedia:
      "https://es.wikipedia.org/wiki/Teodoro_S%C3%A1nchez_de_Bustamante",
  },
  {
    codigo: "17",
    nombre: "Pedro Ignacio de Castro Barros",
    nacimiento: "31 de julio de 1777, Chuquis, Argentina.",
    fallecimiento: "17 de abril de 1849, Santiago de Chile, Chile (71 años).",
    nacionalidad: "Argentina",
    profesion: "Sacerdote y político.",
    distrito: "La Rioja",
    resumen:
      "Sacerdote y político argentino, miembro de la Asamblea del Año XIII y del Congreso de Tucumán, que declaró la Independencia de las Provincias Unidas del Río de la Plata el 9 de julio de 1816.",
    habilidades: [
      "★★☆☆☆ Derecho",
      "★★★☆☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★★ Teología",
    ],
    experiencia: [
      "1841 - Docente en la Universidad Nacional de Chile.",
      "1816 a 1819 - Asesor económico del gobierno de Juan Martín Pueyrredón.",
      "1816 - Diputado para el Congreso de Tucumán.",
      "1804 - Fundó en la Rioja una escuela y un Colegio.",
      "1800 a 1803 - Profesor en la Universidad de Córdoba.",
    ],
    educacion: ["1800 - Recibido de doctor en Teología"],
    aficiones:
      "Férreo defensor del partido unitario; escritor de tratados sobre política e iglesia; partidario de la libertad de vientres; defensor de una constitución monárquica.",
    imagen: "../img/CastroBarrosPedroIgnacio.jpg",
    youtube: "https://www.youtube.com/watch?v=GMmKtGwd6sk",
    wikipedia: "https://es.wikipedia.org/wiki/Pedro_Ignacio_de_Castro_Barros",
  },
  {
    codigo: "18",
    nombre: "Tomás Godoy Cruz",
    nacimiento: "6 de marzo de 1791, Mendoza, Argentina.",
    fallecimiento: "15 de marzo de 1852, Mendoza, Argentina (61 años).",
    nacionalidad: "Argentina",
    profesion: "Político",
    distrito: "Mendoza",
    resumen:
      " Político argentino, diputado para el Congreso de Tucumán de 1916, gobernador de Mendoza entre 1820 y 1822.",
    habilidades: [
      "★★☆☆☆ Derecho",
      "★★★★★ Política",
      "★★☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1830 - Segundo período como Gobernador de Mendoza.",
      "1820 a 1822 - Gobernador de la Provincia de Mendoza.",
      "1816 - Diputado para el Congreso de Tucumán.",
      "1814 - Fundó una fábrica de pólvora en Mendoza.",
    ],
    educacion: [
      "1813 - Graduado en bachiller en Filosofía, Cánones y Leyes - Universidad de San Felipe, Chile.",
    ],
    aficiones:
      "Colaboró con José de San Martín en la preparación de su expedición libertadora, comprometiendo su fortuna personal en el equipamiento del Ejército de los Andes. Defendor de los ideales del partido unitario. Afinidad por la agricultura y la cría de gusanos de seda.",
    imagen: "../img/GodoyCruzTomas.jpg",
    youtube: "https://www.youtube.com/watch?v=rq0RVw5lzt0",
    wikipedia: "https://es.wikipedia.org/wiki/Tom%C3%A1s_Godoy_Cruz",
  },
  {
    codigo: "19",
    nombre: "Juan Agustín Maza",
    nacimiento: "4 de mayo de 1784, Mendoza, Argentina.",
    fallecimiento: "11 de junio de 1830, Malargüe, Argentina.",
    nacionalidad: "Argentina",
    profesion: "Abogado y político.",
    distrito: "Mendoza",
    resumen:
      "Jurisconsulto y político argentino, formó parte del Congreso de Tucumán.",
    habilidades: [
      "★★★☆☆  Derecho",
      "★★★★☆ Política",
      "★☆☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1829 - Presidente de la Junta de Representantes y también ministro de Gobierno.",
      "1824 - Gobernador interino de Mendoza.",
      "1816 - Diputado en el Congreso de Tucumán.",
    ],
    educacion: [
      "1807 - Doctor en derecho civil, Real Universidad de San Felipe de la Capitanía General de Chile.",
    ],
    aficiones:
      "Realizó importantes donaciones para el ejército de los andes. Compartió las ideas del partido federal.",
    imagen: "../img/MazaJAgustin.jpg",
    youtube: "https://www.youtube.com/watch?v=aPqjv9Ou-Bs&t=138s",
    wikipedia: "https://es.wikipedia.org/wiki/Juan_Agust%C3%ADn_Maza",
  },
  {
    codigo: "20",
    nombre: "José Ignacio de Gorriti",
    nacimiento: "30 de julio de 1770, San Salvador de Jujuy, Argentina.",
    fallecimiento: "10 de noviembre de 1835, Chuquisaca, Bolivia (65 años).",
    nacionalidad: "Argentina",
    profesion: "Abogado, militar y político.",
    distrito: "Salta",
    resumen:
      " Abogado, militar y político argentino, que se destacó por su ayuda y acción en la Guerra de Independencia; fe reiteradas veces gobernador de la provincia de Salta y representó a esta provincia como diputado en el Congreso de Tucumán de 1816.",
    habilidades: [
      "★★☆☆☆ Derecho",
      "★★★★☆ Política",
      "★★★★★ Militar",
      "★★★☆☆ Teología",
    ],
    experiencia: [
      "1831 - Gobernador delegado.",
      "1827 a 1829 - Segundo período ante la Gobernacion de Salta.",
      "1821 a 1825 - Gobernador progresista de Salta.",
      "1821 - Venció al coronel realista Guillermo Marquiegui.",
      "1819 a 1821 - Gobernador interino de Salta.",
      "1819 - Senador.",
      "1817 - Avocado a la lucha contra los realistas. ",
      "1816 - Diputado por Salta para el Congreso de Tucumán.",
      " Formó la Partida de Baqueanos para el Ejército del Norte y el primer Cuerpo de Patriotas Decididos que se incorporó a las fuerzas que comandaba Martín Miguel de Güemes.",
    ],
    educacion: [
      "1789 - Doctor en cánones por la  Universidad Mayor Real y Pontificia San Francisco Xavier de Chuquisaca.",
      "1782 a 1788 - Cursó en el Real Colegio Monserrat, Córdoba.",
      "De niño estudió con los padres franciscanos.",
    ],
    aficiones:
      "Afín al partido unitario. Administrador de fincas, afinidad por la lectura filosófica y jurídica. Financió al ejercito argentino: contra las invasiones inglesas y a Güemes.  introdujo la vacunación antivariólica, fomentó la educación y la beneficencia, y legisló sobre el ejercicio de la medicina, la sepultura y nombramientos e incompatibilidades del Poder Judicial.",
    imagen: "../img/GorritiJoseIgnaciode.jpg",
    youtube: "https://www.youtube.com/watch?v=3ahcq7PlyO8",
    wikipedia: "https://es.wikipedia.org/wiki/Jos%C3%A9_Ignacio_de_Gorriti",
  },
  {
    codigo: "21",
    nombre: "Justo Santa María de Oro.",
    nacimiento: "30 de julio de 1772, San Juan, Argentina.",
    fallecimiento: "19 de octubre de 1836, San Juan, Argentina.",
    nacionalidad: "Argentina",
    profesion: "Sacerdote y político.",
    distrito: "San Juan",
    resumen:
      "Sacerdote argentino, defensor del republicanismo y diputador para el Congreso de Tucumán.",
    habilidades: [
      "★★☆☆☆ Derecho",
      "★★★☆☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★★ Teología",
    ],
    experiencia: [
      "1830 - Fue consagrado como Obispo de San Juan.",
      "1828 - Vicario apostólico para la diócesis de San Juan. Bajo este cargo construyó la Catedral, mejoró las escuelas religiosas.",
      "1816 - Diputado para el Congreso de Tucumán.",
    ],
    educacion: ["1789 - Orden de los hermanos Dominicos en Chile. "],
    aficiones:
      "Férreo defensor de la forma republicana de gobierno por su frase 'hay que consultar a los pueblos'. En el Congreso de Tucumán sus palabras fueron 'se dará la batalla a favor de la soberanía del pueblo' y por eso aparece la tesis de la monarquía constitucional o 'Yo el Rey', enfrentada con la de la república o 'Nosotros los pueblos'.",
    imagen: "../img/SantamariadeOroJusto.jpg",
    youtube: "https://www.youtube.com/watch?v=qMzO-DMvTHQ",
    wikipedia: "https://es.wikipedia.org/wiki/Justo_Santa_Mar%C3%ADa_de_Oro",
  },
  {
    codigo: "22",
    nombre: "Pedro Francisco de Uriarte",
    nacimiento: "29 de junio de 1758, Santiago del Estero, Argentina.",
    fallecimiento: "30 de agosto de 1839, Loreto, Argentina (81 años).",
    nacionalidad: "Argentina",
    profesion: "Sacerdote y Político.",
    distrito: "Santiago del Estero",
    resumen:
      "Sacerdote y político que participó activamente en el período de independencia argentina. A lo largo de su vida política ocupó diferentes cargos, entre ellos el de diputado por Santiago del Estero ante el Congreso de Tucumán.",
    habilidades: [
      "★☆☆☆☆ Derecho",
      "★★★★☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★★ Teología",
    ],
    experiencia: [
      "1824 a 1825 - Ministro elegido por la venerable Tercera Orden de Santiago.",
      "1818 - Propuso la repartición de tierras y fue precursos de la Ley de Colonización.",
      "1816 - Diputado para el Congreso de Tucumán.",
      "1810 - Diputado por Santiago del Estero para la Junta Grande.",
      "1802 - Fue designado como vicario foráneo de Santiago del Estero por el Obispo de Córdoba.",
      "1793 - Se creó el curato de Loreto, en Santiago del Estero, donde fue nombrado por concurso como su primer titular.",
      "1786 - Trabajó como capellán en la Casa de Ejercicios en Buenos Aires.",
    ],
    educacion: [
      "1783 - Doctor en cánones por la Universidad Nacional de Córdoba.",
      "Aprendió las primeras letras en la escuela de los orden franciscana.",
    ],
    aficiones:
      "Hombre generoso y estuvo del lado de los patriotas en 1810, ayudando con dinero cuando había que donar a las fuerzas patrias.",
    imagen: "../img/UriartePedro.jpg",
    youtube: "https://www.youtube.com/watch?v=oChsKDutgCs",
    wikipedia: "https://es.wikipedia.org/wiki/Pedro_Francisco_de_Uriarte",
  },
  {
    codigo: "23",
    nombre: "Pedro León Díaz Gallo",
    nacimiento: "1782, Santiago del Estero, Argentina.",
    fallecimiento: "16 de febrero de 1852, San Miguel de Tucumán. (70 años).",
    nacionalidad: "Argentina",
    profesion: "Sacerdote y político",
    distrito: "Santiago del Estero",
    resumen:
      "Sacerdote y político que se desempeñó como diputado por Santiago del Estero durante el Congreso de Tucumán de 1816",
    habilidades: [
      "★☆☆☆☆  Derecho",
      "★★★☆☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★★  Teología",
    ],
    experiencia: [
      "1838 - Se encargó del gobierno de la diócesis de Santiago.",
      "1821 - firmó el Tratado de Vinará. ",
      "1819 - Participó de la redacción de la constitución unitaria.",
      "1816 - Mientras se hallaba al frente del curato de su ciudad, fue elegido diputado al Congreso de Tucumán.",
      "1815 - Participó del Cabildo Abierto.",
    ],
    educacion: [
      "En Santiago del Estero inició su carrera de sacerdote en Loreto, junto a Pedro Francisco de Uriarte.",
      "Obtuvo el título de «maestro en artes» (filosofía) en la Universidad de San Carlos.",
      "1799 - Ingresó al Colegio de Monserrat, en Córdoba, donde se ordenó de presbítero.",
    ],
    aficiones: "Afín a las ideas unitarias.",
    imagen: "../img/GalloPedroLeon.jpg",
    youtube: "https://www.youtube.com/watch?v=4W_z6zziTYg",
    wikipedia: "https://es.wikipedia.org/wiki/Pedro_Le%C3%B3n_D%C3%ADaz_Gallo",
  },
  {
    codigo: "24",
    nombre: "Pedro Miguel Aráoz",
    nacimiento: "20 de junio de 1759, San Miguel de Tucumán, Argentina.",
    fallecimiento:
      "18 de junio de 1832, San Miguel de Tucumán, Argentina (72 años)",
    nacionalidad: "Argentina",
    profesion: "Sacerdote y político.",
    distrito: "Tucumán",
    resumen:
      "Religioso argentino, diputado al Congreso de Tucumán por esta provincia, siendo uno de los firmantes del Acta de la Declaración de independencia de la Argentina el 9 de julio de 1816.",
    habilidades: [
      "★☆☆☆☆ Derecho",
      "★★★☆☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★★ Teología",
    ],
    experiencia: [
      "1816 - Fue elegido diputado para el Congreso de Tucumán. ",
      "1799 - Cura párroco y vicario. ",
      "1785 a 1788  profesor de Filosofía y rector en el Real Colegio de San Carlos de Buenos Aires.",
    ],
    educacion: [
      "1782 - Se ordenó sacerdote y se recibió de Dr. de Teología por la Universidad Nacional de Córdoba.",
      "Estudió teología en Buenos Aires, en el Real Colegio de San Carlos.",
      "Recibió su instrucción inicial en establecimientos religiosos de la ciudad de San Miguel de Tucumán.",
    ],
    aficiones:
      "Gran orador, fue designado en 1808 para pronunciar la oración fúnebre por los caídos en la defensa de Buenos Aires en la primera invasión inglesa de 1806, entre los que se encontraban numerosos tucumanos. Estaba a favor de la conformación de la Gran República de Tucumán. De extraordinaria cultura, era considerado 'uno de los talentos más distinguidos de la época'.",
    imagen: "../img/AraozPedroMiguel.jpg",
    youtube: "https://www.youtube.com/watch?v=4W_z6zziTYg&t=2s",
    wikipedia: "https://es.wikipedia.org/wiki/Pedro_Miguel_Ar%C3%A1oz",
  },
  {
    codigo: "25",
    nombre: "José Ignacio Thames",
    nacimiento: "15 de agosto de 1762, San Miguel de Tucumán, Argentina.",
    fallecimiento:
      "9 de febrero de 1832, San Miguel de Tucumán, Argentina (69 años).",
    nacionalidad: "Argentina",
    profesion: "Sacerdote y político.",
    distrito: "Tucumán",
    resumen:
      "Sacerdote y político argentino, siendo uno de los firmantes por Tucumán de la Declaración de la Independencia de las entonces conocidas como Provincias Unidas en Sudamérica.",
    habilidades: [
      "★★★★★ Derecho",
      "★★★★☆ Política",
      "★☆☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1824 a 1825 - Párroco de El Alto.",
      "1821 - Diputado.",
      "1818 - Elegido vicepresidente en el Congreso de Buenos Aires.",
      "1816 - Diputado en el Congreso de Tucumán.",
      "1813 - Canónigo de la catedral de Salta.",
      "1789 - Designado Cura párroco de El Alto, provincia de Catamarca.",
    ],
    educacion: [
       "1784 - Doctor en Teología, Universidad Nacional de Córdoba.",
    ],
    aficiones: "Propugnó una monarquía inca como forma de gobierno.",
    imagen: "../img/ThamesJoseIgnacio.jpg",
    youtube: "https://www.youtube.com/watch?v=Wp5yUaBSdIw",
    wikipedia: "https://es.wikipedia.org/wiki/Jos%C3%A9_Ignacio_Thames",
  },
  {
    codigo: "26",
    nombre: "Pedro Ignacio Rivera",
    nacimiento: "1753, Mizque, Bolivia.",
    fallecimiento: "17 de febrero de 1833, Buenos Aires, Argentina (80 años).",
    nacionalidad: "Argentina y boliviana.",
    profesion: "Abogado y político.",
    distrito: "Mizque",
    resumen:
      "Abogado y político que actuó como diputado por Mizque durante el Congreso de Tucumán de 1816, siendo por tanto uno de los firmantes de la Declaración de la Independencia de las entonces conocidas como Provincias Unidas en Sudamérica.",
    habilidades: [
      "★★★★☆ Derecho",
      "★★★★☆ Política",
      "★★★☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "1819 - Intervino en los debates y sanción de la Constitución de 1819.",
      "1816 - Diputado en el Congreso de Tucumán.",
      "1815 - Ejerció la vicepresidencia de la Asamblea General Constituyente de Mizque.",
      "1809 - mediador entre la Iglesia y el pueblo, en el movimiento revolucionario contra el Presidente García Pizarro.",
      "Trabajó como minero y azoguero en Oruro.",
      "Se desempeñó con el grado de coronel como jefe de milicias en la ciudad de Mizque.",
    ],
    educacion: [
      "1793 - Obtuvo el título en derecho civil en la Universidad Mayor Real y Pontificia San Francisco Xavier de Chuquisaca.",
    ],
    aficiones:
      "A favor de un gobierno de monarquia temperada, bajo la dinastía de los antiguos incas. Autor de un proyecto de formación del ejército.",
    imagen: "../img/RiveraPedroIgnacio.jpg",
    youtube: "https://www.youtube.com/watch?v=BbyTSgM9zn8",
    wikipedia: "https://es.wikipedia.org/wiki/Pedro_Ignacio_Rivera",
  },
  {
    codigo: "27",
    nombre: "Mariano Sánchez de Loria",
    nacimiento: "24 de septiembre de 1774, Chuquisaca, Bolivia.",
    fallecimiento: "2 de agosto de 1842, Potosí, Bolivia (67 años).",
    nacionalidad: "Boliviana",
    profesion: "Abogado, político y sacerdote",
    distrito: "Charcas",
    resumen:
      "Fue un abogado, político y posteriormente sacerdote boliviano. Fue diputado por Charcas del Congreso de Tucumán que el 9 de julio de 1816 declaró la Independencia argentina.",
    habilidades: [
      "★★★★☆ Derecho",
      "★★★★☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★☆ Teología",
    ],
    experiencia: [
      "1817 - Canónigo de la Catedral de Charcas. ",
      "1817 - Trabajó como abogado independiente.",
      "1816 - Elegido para ser diputado en el Congreso de Tucumán.",
      "1809 - Apoyó la revolución en su ciudad.",
    ],
    educacion: [
      "1817 - Se ordenó sacerdote.",
      "Doctor en Jurisprudencia y leyes canónicas.",
    ],
    aficiones:
      "Apoyó el proyecto de monarquía a cargo de una familia real inca para las Provincias Unidas del Río de la Plata.",
    imagen: "../img/SanchezdeLoriaMariano.jpg",
    youtube: "https://www.youtube.com/watch?v=UNNogdywjVo&t=54s",
    wikipedia: "https://es.wikipedia.org/wiki/Mariano_S%C3%A1nchez_de_Loria",
  },
  {
    codigo: "28",
    nombre: "José Severo Malabia",
    nacimiento: "15 de mayo de 1787, Chuquisaca, Bolivia.",
    fallecimiento: "1849, Buenos Aires, Argentina (62 años).",
    nacionalidad: "Argentina y boliviana.",
    profesion: "Abogado y político.",
    distrito: "Charcas",
    resumen:
      " Abogado y político argentino de origen altoperuano, miembro del Congreso de Tucumán, que declaró la Independencia argentina.",
    habilidades: [
      "★★★★☆ Derecho",
      "★★★★☆ Política",
      "★☆☆☆☆ Militar",
      "★☆☆☆☆ Teología",
    ],
    experiencia: [
      "Embajador de Bolivia en Lima.",
      "Embajador de Bolivia en Buenos Aires.",
      "Ocupó cargos oficiales en Charcas.",
      "1823 - Secretario del embajador ante el virrey del Perú, general Juan Gregorio de Las Heras.",
      "1819 - Firmó la constitución unitaria de 1819 en el Congreso de Buenos Aires.",
      "1816 - Diputado en el Congreso de Tucumán.",
      "Ocupó cargos administrativos en la ciudad de Tupiza, en el extremo sur de la actual Bolivia.",
    ],
    educacion: [
      "Doctor en Jurisprudencia  -  Universidad Mayor Real y Pontificia San Francisco Xavier de Chuquisaca.",
    ],
    aficiones:
      "Apoyó la Revolución de Chuquisaca del 25 de mayo de 1809.  Era de tendencia monárquica, y defendió su ideología con tenacidad, hasta casi lograr que se coronara un rey en la actual Argentina.",
    imagen: "../img/MalabiaJoseSevero.jpg",
    youtube: "https://www.youtube.com/watch?v=Bb4t9X5Vqyk",
    wikipedia: "https://es.wikipedia.org/wiki/Jos%C3%A9_Severo_Malabia",
  },
  {
    codigo: "29",
    nombre: "José Andrés Pacheco de Melo",
    nacimiento: "17 de octubre de 1779, Salta, Argentina.",
    fallecimiento: "Entre 1820 y 1833, posiblemente en Bolivia o Argentina.",
    nacionalidad: "Argentina",
    profesion: "Sacerdote y político.",
    distrito: "Chichas",
    resumen:
      "Sacerdote católico y político argentino. Fue diputado por Chichas (en el actual Bolivia) para el Congreso de Tucumán, que declaró la Independencia el 9 de julio de 1816.",
    habilidades: [
      "★☆☆☆☆ Derecho",
      "★★★☆☆ Política",
      "★☆☆☆☆ Militar",
      "★★★★★ Teología",
    ],
    experiencia: [
      "1825 - Pacificador en San Juan.",
      "1821 - Pacificador en Córdoba.",
      "1818 - Ministro de Gobierno de Mendoza.",
      "1816 - Diputado en el Congreso de Tucumán.",
      "1810 - Cura en Chichas, Bolivia.",
    ],
    educacion: ["1801 - Seminario de Nuestra Señora de Loreto, en Córdoba."],
    aficiones: " Asistió   a las tropas revolucionarias en el Alto Perú.",
    imagen: "../img/PachecodeMeloJoseAndres.jpg",
    youtube: "https://www.youtube.com/watch?v=4W_z6zziTYg&t=3s",
    wikipedia:
      "https://es.wikipedia.org/wiki/Jos%C3%A9_Andr%C3%A9s_Pacheco_de_Melo",
  },
];

const datosMauricio = [
  {
    codigo: "1",
    nombre: "Mauricio Javier Alonso",
    nacimiento: "10/11/1981",
    nacionalidad: "Argentina",
    profesion: "Contador Público",
    mail: "program.alonso@gmail.com",
    resumen:
      "Contador público, magister en administración y especialista en impuestos. Senior en evaluación de proyectos de inversión y formulación de planes de negocio. Consultoría en BI, finanzas operativas, planificación tributaria y estrategia de negocios. Proactivo, versátil y organizado, apasionado en el desarrollo constante de habilidades.",
    habilidades: [
      "★★★★★ Evaluación de proyectos, análisis de estados contables e indicadores",
      "★★★★☆ Manejo de Excel, Word y PowerPoint",
      "★★★★☆ Idioma Inglés",
      "★★★☆☆ Herramientas de análisis de datos",
    ],
    experiencia: [
      "03/2006 - Actualmente - Evaluador de Proyectos de Inversión - Consejo Federal de Inversiones - Unidad de Enlace Córdoba.",
      "01/2006 - Actualmente - Profesional Independiente, en estudio contable propio. ",
      "06/2018 - 11/2019 - Consultor en Planes de Negocio  - Agencia Córdoba Turismo SEM - Córdoba.",
      "10/2011 - 01/2013 - Asesor - Comisión Pymes - Consejo Profesional de Ciencias Económicas de Córdoba.",
    ],
    educacion: [
      "08/2021 - 01/2022 - Certificado en Business Analytics -  Universidad Siglo 21",
      "01/2012 - 12/2013 - Magíster en Administración de Negocio - Universidad Nacional de Córdoba",
      "01/2006 - 12/2014 - Especialista en Tributación - Universidad Nacional de Córdoba",
      "01/2000 - 12/2005 - Contador Público - Universidad Siglo 21",
    ],
    aficiones: ["Programación web (nivel Trainee)", "Guitarra", "Ajedrez"],
    imagen: "../img/MauricioJavierAlonso.jpg",
    linkedin: "https://www.linkedin.com/in/mauriciojavieralonso/",
  },
  {
    codigo: "2",
    nombre: "Mauricio Javier Alonso",
    nacimiento: "10/11/1981",
    nacionalidad: "Argentina",
    profesion: "Accountant ",
    mail: "program.alonso@gmail.com",
    resumen:
      "Accountant, master of administration, and tax specialist Senior in the evaluation of investment projects and formulation of business plans; consultant in BI, operational finance, tax planning, and business strategy. Proactive, versatile, and organized, I am passionate about constantly developing skills.",
    habilidades: [
      "★★★★★ Evaluation of projects, analysis of financial statements and indicators.",
      "★★★★☆ Management of Excel, Word and PowerPoint ",
      "★★★★☆ English language",
      "★★★☆☆ Data Analysist",
    ],
    experiencia: [
      "03/2006 - Current - Investment Project Evaluator - Federal Investment Council - Cordoba headquarters.",
      "01/2006 - Current - Independent accountant. ",
      "06/2018 - 11/2019 - Business Plan Consultant - Cordoba Tourism Agency SEM - Cordoba.",
      "10/2011 - 01/2013 - Advisor - SME Commission - CPCEC Cordoba",
    ],
    educacion: [
      "08/2021 - 01/2022 - Certificate in Business Analytics -  Siglo 21 University",
      "01/2012 - 12/2013 - Master of Business Administration- National University of Cordoba",
      "01/2006 - 12/2014 - Tax Specialist - National University of Cordoba ",
      "01/2000 - 12/2005 - Accountant - Siglo 21 University",
    ],
    aficiones: ["Web programming (Trainee Level)", "Guitar", "Chess"],
    imagen: "../img/MauricioJavierAlonso.jpg",
    linkedin: "https://www.linkedin.com/in/mauriciojavieralonso/",
  },
];


const frases = [
  "Era universal, constante y decidido el clamor del territorio entero por su emancipacion solemne del poder despótico de los reyes de España (Acta de declaración de la Independencia).",
  "Declaramos solemnemente a la faz de la tierra, que es voluntad unánime e indubitable de estas Provincias romper los violentos vínculos que las ligaban a los reyes de España, recuperar los derechos de que fueron despojadas, e investirse del alto carácter de una nacion libre e independiente del rey Fernando VII, sus sucesores y metrópoli (Acta de declaración de la Independencia).",
  "Cuando hay libertad, todo lo demás sobra (José de San Martín).",
  "No hay respeto humano que deba guardarse cuando se trata de la seguridad y libertad americanas (José de San Martín).",
  "La vida es nada si la libertad se pierde (Manuel Belgrano).",
  "Un pueblo culto nunca puede ser esclavizado (Manuel Belgrano).",
  "Quiero más una libertad peligrosa que una servidumbre tranquila (Mariano Moreno).",
  "Ningún tirano haría progresos si no hubieran malvados que conducidos por el egoísmo y arrastrados por el torrente de las pasiones antisociales no sirviesen de apoyo al trono erigido por los déspotas entre las ruinas de la virtud y derechos más augustos del hombre... Así es que apenas medió en la Capital del Río de la Plata la feliz revolución que hizo temblar y estremecer a los enemigos del hombre (Juan José Castelli).",
  "Recordemos a nuestro pueblo que la patria no es el suelo. Tenemos suelo hace tres siglos, y sólo tenemos patria desde 1810. La patria es la libertad, es el orden, la riqueza, la civilización organizados en el suelo nativo, bajo su enseña y en su nombre (Juan Bautista Alberdi).",
  "Sirvo a la patria sin otro objeto que el de verla constituida, ése es el premio al que aspiro (Manuel Belgrano).",
  "Y no quede duda de que es el pueblo el que confiere la autoridad o mando (Cornelio Saavedra).",
];
